// Mock data for vehicles
export const mockVehicles = [
  {
    id: 'v001',
    vehicleCode: 'TRK-001',
    name: 'Isuzu Giga FVZ',
    type: 'Truk Berat',
    location: 'Depot A - Cikarang',
    status: 'critical',
    healthScore: 34,
    downtimeRisk: 'high',
    lastMaintenanceDate: '2026-03-10',
    nextMaintenanceDate: '2026-04-28',
    mileage: 187500,
    operatingHours: 9210,
    issueCount: 8,
    repeatedIssues: ['Overheating', 'Oli Bocor'],
    recommendation: 'Segera lakukan pengecekan mesin dan ganti oli. Kendaraan berisiko tinggi breakdown.',
  },
  {
    id: 'v002',
    vehicleCode: 'TRK-002',
    name: 'Mitsubishi Fuso FJ',
    type: 'Truk Sedang',
    location: 'Depot B - Bekasi',
    status: 'warning',
    healthScore: 61,
    downtimeRisk: 'medium',
    lastMaintenanceDate: '2026-04-01',
    nextMaintenanceDate: '2026-05-15',
    mileage: 134200,
    operatingHours: 6540,
    issueCount: 4,
    repeatedIssues: ['Kampas Aus'],
    recommendation: 'Jadwalkan penggantian kampas rem sebelum akhir bulan.',
  },
  {
    id: 'v003',
    vehicleCode: 'VAN-001',
    name: 'Toyota HiAce Commuter',
    type: 'Van Penumpang',
    location: 'Pool Kendaraan - HQ',
    status: 'healthy',
    healthScore: 88,
    downtimeRisk: 'low',
    lastMaintenanceDate: '2026-04-15',
    nextMaintenanceDate: '2026-06-20',
    mileage: 54300,
    operatingHours: 2870,
    issueCount: 1,
    repeatedIssues: [],
    recommendation: 'Kondisi baik. Lanjutkan jadwal perawatan rutin.',
  },
  {
    id: 'v004',
    vehicleCode: 'TRK-003',
    name: 'Hino 500 FM260JD',
    type: 'Truk Berat',
    location: 'Depot A - Cikarang',
    status: 'warning',
    healthScore: 57,
    downtimeRisk: 'medium',
    lastMaintenanceDate: '2026-03-22',
    nextMaintenanceDate: '2026-05-01',
    mileage: 221000,
    operatingHours: 10920,
    issueCount: 6,
    repeatedIssues: ['Getaran Abnormal', 'Suara Kasar'],
    recommendation: 'Periksa sistem transmisi dan suspensi. Mileage tinggi, pertimbangkan overhaul.',
  },
  {
    id: 'v005',
    vehicleCode: 'PKP-001',
    name: 'Daihatsu Gran Max PU',
    type: 'Pick Up',
    location: 'Depot C - Karawang',
    status: 'healthy',
    healthScore: 82,
    downtimeRisk: 'low',
    lastMaintenanceDate: '2026-04-10',
    nextMaintenanceDate: '2026-06-01',
    mileage: 42100,
    operatingHours: 2140,
    issueCount: 2,
    repeatedIssues: [],
    recommendation: 'Kondisi baik. Cek tekanan ban secara berkala.',
  },
  {
    id: 'v006',
    vehicleCode: 'BUS-001',
    name: 'Mercedes-Benz OH 1626',
    type: 'Bus',
    location: 'Pool Bus - Cibitung',
    status: 'critical',
    healthScore: 28,
    downtimeRisk: 'high',
    lastMaintenanceDate: '2026-02-20',
    nextMaintenanceDate: '2026-04-25',
    mileage: 312800,
    operatingHours: 15630,
    issueCount: 11,
    repeatedIssues: ['Overheating', 'Rem Blong', 'Oli Bocor'],
    recommendation: 'URGENT: Kendaraan tidak layak beroperasi. Hentikan penggunaan dan lakukan perbaikan menyeluruh.',
  },
  {
    id: 'v007',
    vehicleCode: 'VAN-002',
    name: 'Isuzu Elf Mini Bus',
    type: 'Mini Bus',
    location: 'Pool Kendaraan - HQ',
    status: 'healthy',
    healthScore: 91,
    downtimeRisk: 'low',
    lastMaintenanceDate: '2026-04-20',
    nextMaintenanceDate: '2026-06-30',
    mileage: 38900,
    operatingHours: 1950,
    issueCount: 0,
    repeatedIssues: [],
    recommendation: 'Kondisi prima. Tidak ada tindakan yang diperlukan.',
  },
  {
    id: 'v008',
    vehicleCode: 'TRK-004',
    name: 'UD Trucks Quester',
    type: 'Truk Berat',
    location: 'Depot B - Bekasi',
    status: 'warning',
    healthScore: 64,
    downtimeRisk: 'medium',
    lastMaintenanceDate: '2026-03-30',
    nextMaintenanceDate: '2026-05-10',
    mileage: 178400,
    operatingHours: 8830,
    issueCount: 5,
    repeatedIssues: ['Filter Tersumbat'],
    recommendation: 'Ganti filter bahan bakar dan periksa sistem injeksi.',
  },
]

// Maintenance history
export const mockMaintenanceHistory = [
  {
    id: 'mh001', vehicleId: 'v001', date: '2026-03-10',
    component: 'Mesin', issue: 'Overheating', severity: 'high',
    technician: 'Budi Santoso', note: 'Suhu mesin melebihi batas normal saat operasi jarak jauh',
    actionTaken: 'Flush coolant, ganti thermostat, bersihkan radiator',
  },
  {
    id: 'mh002', vehicleId: 'v001', date: '2026-02-14',
    component: 'Mesin', issue: 'Oli Bocor', severity: 'medium',
    technician: 'Agus Wijaya', note: 'Ditemukan oli bocor di area gasket',
    actionTaken: 'Ganti gasket mesin, kencangkan baut blok mesin',
  },
  {
    id: 'mh003', vehicleId: 'v001', date: '2026-01-08',
    component: 'Ban', issue: 'Aus', severity: 'medium',
    technician: 'Budi Santoso', note: 'Tapak ban depan kanan sudah habis',
    actionTaken: 'Ganti ban depan kiri dan kanan, rotasi ban belakang',
  },
  {
    id: 'mh004', vehicleId: 'v001', date: '2025-12-01',
    component: 'Rem', issue: 'Kampas Aus', severity: 'high',
    technician: 'Dedi Rahman', note: 'Kampas rem depan menipis, suara berdecit',
    actionTaken: 'Ganti kampas rem depan kiri dan kanan',
  },
  {
    id: 'mh005', vehicleId: 'v002', date: '2026-04-01',
    component: 'Rem', issue: 'Kampas Aus', severity: 'medium',
    technician: 'Rudi Hermawan', note: 'Kampas rem belakang mulai menipis',
    actionTaken: 'Pengamplasan dan penyesuaian rem, monitoring',
  },
  {
    id: 'mh006', vehicleId: 'v002', date: '2026-03-01',
    component: 'Ban', issue: 'Tekanan Rendah', severity: 'low',
    technician: 'Rudi Hermawan', note: 'Ban belakang kanan tekanan rendah',
    actionTaken: 'Isi angin, cek valve, tambal bocor kecil',
  },
  {
    id: 'mh007', vehicleId: 'v003', date: '2026-04-15',
    component: 'Lampu', issue: 'Redup', severity: 'low',
    technician: 'Sisi Margono', note: 'Lampu depan kanan redup',
    actionTaken: 'Ganti bohlam lampu depan kanan',
  },
  {
    id: 'mh008', vehicleId: 'v004', date: '2026-03-22',
    component: 'Mesin', issue: 'Getaran Abnormal', severity: 'high',
    technician: 'Agus Wijaya', note: 'Getaran tidak normal saat RPM tinggi',
    actionTaken: 'Balancing mesin, cek mounting mesin',
  },
  {
    id: 'mh009', vehicleId: 'v004', date: '2026-02-28',
    component: 'Transmisi', issue: 'Suara Kasar', severity: 'high',
    technician: 'Budi Santoso', note: 'Suara kasar dari area transmisi saat pindah gigi',
    actionTaken: 'Ganti oli transmisi, cek synchronizer',
  },
  {
    id: 'mh010', vehicleId: 'v006', date: '2026-02-20',
    component: 'Rem', issue: 'Blong', severity: 'critical',
    technician: 'Dedi Rahman', note: 'KRITIS: Rem tidak berfungsi pada saat uji jalan',
    actionTaken: 'Ganti master cylinder, bleeding rem, ganti selang rem',
  },
  {
    id: 'mh011', vehicleId: 'v006', date: '2026-01-15',
    component: 'Mesin', issue: 'Overheating', severity: 'critical',
    technician: 'Agus Wijaya', note: 'Mesin overheating parah, ada asap dari kap mesin',
    actionTaken: 'Overhaul radiator, ganti water pump, ganti coolant',
  },
  {
    id: 'mh012', vehicleId: 'v008', date: '2026-03-30',
    component: 'Sistem Bahan Bakar', issue: 'Filter Tersumbat', severity: 'medium',
    technician: 'Rudi Hermawan', note: 'Konsumsi BBM meningkat, performa menurun',
    actionTaken: 'Ganti filter bahan bakar, bersihkan injector',
  },
]

// Dashboard summary
export const mockDashboardSummary = {
  totalVehicles: 8,
  healthy: 3,
  warning: 3,
  critical: 2,
  dueSoon: 3,
  highRisk: 2,
}

// Trend data for charts
export const mockIssueTrend = [
  { month: 'Nov', issues: 5, maintenance: 3 },
  { month: 'Des', issues: 8, maintenance: 6 },
  { month: 'Jan', issues: 11, maintenance: 5 },
  { month: 'Feb', issues: 9, maintenance: 7 },
  { month: 'Mar', issues: 13, maintenance: 9 },
  { month: 'Apr', issues: 7, maintenance: 5 },
]

export const mockComponentDistribution = [
  { component: 'Mesin', count: 8 },
  { component: 'Rem', count: 6 },
  { component: 'Ban', count: 5 },
  { component: 'Suspensi', count: 4 },
  { component: 'Transmisi', count: 3 },
  { component: 'Lampu', count: 2 },
  { component: 'Lainnya', count: 3 },
]

export const mockHealthOverview = [
  { name: 'Sehat (80-100)', value: 3, color: '#10b981' },
  { name: 'Peringatan (60-79)', value: 3, color: '#f59e0b' },
  { name: 'Kritis (<60)', value: 2, color: '#ef4444' },
]

// Alerts
export const mockAlerts = [
  {
    id: 'al001', vehicleId: 'v006', vehicleCode: 'BUS-001', vehicleName: 'Mercedes-Benz OH 1626',
    type: 'critical_risk', riskLevel: 'high',
    message: 'Kendaraan tidak layak beroperasi — 3 isu kritis belum tertangani',
    predictedNextMaintenance: '2026-04-25',
    recommendation: 'Hentikan operasi segera. Lakukan overhaul menyeluruh.',
    daysUntilMaintenance: 1,
  },
  {
    id: 'al002', vehicleId: 'v001', vehicleCode: 'TRK-001', vehicleName: 'Isuzu Giga FVZ',
    type: 'maintenance_due', riskLevel: 'high',
    message: 'Maintenance terjadwal jatuh tempo dalam 4 hari',
    predictedNextMaintenance: '2026-04-28',
    recommendation: 'Jadwalkan service mesin, ganti oli, dan cek sistem pendingin.',
    daysUntilMaintenance: 4,
  },
  {
    id: 'al003', vehicleId: 'v004', vehicleCode: 'TRK-003', vehicleName: 'Hino 500 FM260JD',
    type: 'repeated_issue', riskLevel: 'medium',
    message: 'Isu getaran abnormal berulang 3x dalam 60 hari',
    predictedNextMaintenance: '2026-05-01',
    recommendation: 'Periksa sistem transmisi secara menyeluruh. Kemungkinan masalah struktural.',
    daysUntilMaintenance: 7,
  },
  {
    id: 'al004', vehicleId: 'v002', vehicleCode: 'TRK-002', vehicleName: 'Mitsubishi Fuso FJ',
    type: 'maintenance_due', riskLevel: 'medium',
    message: 'Maintenance terjadwal dalam 21 hari',
    predictedNextMaintenance: '2026-05-15',
    recommendation: 'Siapkan kampas rem baru dan jadwalkan penggantian.',
    daysUntilMaintenance: 21,
  },
  {
    id: 'al005', vehicleId: 'v008', vehicleCode: 'TRK-004', vehicleName: 'UD Trucks Quester',
    type: 'maintenance_due', riskLevel: 'medium',
    message: 'Maintenance terjadwal dalam 16 hari',
    predictedNextMaintenance: '2026-05-10',
    recommendation: 'Ganti filter bahan bakar dan periksa sistem injeksi.',
    daysUntilMaintenance: 16,
  },
]
